(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={orders:'M4 3h16v18H4z M8 7h8 M8 11h8 M8 15h5',tree:'M4 3h6v5H4z M14 16h6v5h-6z M4 16h6v5H4z M7 8v4h10v4 M7 12v4',cart:'M3 3h2l3 13h11l2-9H6 M10 21h.01 M18 21h.01',box:'M3 7l9-5 9 5v10l-9 5-9-5z M3 7l9 5 9-5 M12 12v10',search:'M21 21l-5-5 M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',arrow:'M5 12h14 M14 7l5 5-5 5',back:'M19 12H5 M10 7l-5 5 5 5',refresh:'M20 5v5h-5 M4 19v-5h5 M5 8a8 8 0 0 1 13-4l2 6 M19 16a8 8 0 0 1-13 4l-2-6',check:'M5 12l4 4L19 6',x:'M6 6l12 12 M6 18L18 6',logout:'M9 4H4v16h5 M10 12h11 M16 7l5 5-5 5',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M10 2h4l1 4 4 1 2 4-3 3 1 4-4 2-3-3-4 1-2-4 3-3-1-4 4-2z',grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 7v5l3 2',truck:'M2 5h12v12H2z M14 9h4l4 4v4h-8 M8 19a2 2 0 1 1-4 0 2 2 0 0 1 4 0 M20 19a2 2 0 1 1-4 0 2 2 0 0 1 4 0',factory:'M3 21V9l6 4V8l6 4V3h4v18z M6 17h2 M11 17h2 M16 17h2',bolt:'M13 2L4 14h7l-1 8 10-12h-7z',menu:'M3 6h18 M3 12h18 M3 18h18',trash:'M3 6h18 M8 6V3h8v3 M5 6l1 15h12l1-15 M10 10v7 M14 10v7',info:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M12 10v7 M12 7h.01',user:'M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M4 21v-3a8 8 0 0 1 16 0v3',external:'M14 3h7v7 M21 3l-11 11 M10 3H3v18h18v-7'};
const icon=(n,cl='')=>`<svg class="icon ${cl}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[n]||paths.box}"/></svg>`;
const brand=()=>`<div class="brand"><svg class="brand-symbol" viewBox="0 0 40 36" fill="none" aria-hidden="true"><rect x="3" y="2" width="32" height="32" rx="8" stroke="currentColor" stroke-width="2"/><path d="M13 9h6c12 0 12 18 0 18h-6V9Z" stroke="currentColor" stroke-width="3"/></svg><div><div class="brand-word">DEMO</div><div class="brand-sub">B2B PROCUREMENT</div></div></div>`;
const money=n=>'NT$ '+Number(n).toLocaleString('zh-TW'), fmt=d=>new Date(d).toLocaleString('zh-TW',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}),today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Taipei'}).format(new Date()),uid=()=>crypto.randomUUID();
function read(k,fallback){try{let raw=localStorage.getItem(k);if(raw===null&&k.startsWith('demo-b2b')){const previous=k.replace(/^demo-b2b/,'delta-b2b');raw=localStorage.getItem(previous);if(raw!==null){localStorage.setItem(k,raw);localStorage.removeItem(previous);}}return JSON.parse(raw)??fallback;}catch{return fallback;}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v));}
const storedUrl=read('demo-b2b-url',null),gasUrl=storedUrl===null?PORTAL_CONFIG.gasUrl:storedUrl;
const env=gasUrl||'local-demo',sessionKey='demo-b2b-session:'+env,dbKey='demo-b2b-demo-db:v1';
let session=read(sessionKey,null),state={user:null,catalog:Domain.products,orders:[],cart:[],view:'orders',filter:'all',search:'',page:1,category:'all',type:'all',productSearch:'',orderId:null,menu:false,checkoutKey:null,checkoutForm:null},busy=false,modalPreviousFocus=null;
let toastTimer;
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4200);}
function cartKey(){return 'demo-b2b-cart:'+env+':'+state.user.username;}
function saveCart(){write(cartKey(),state.cart);state.checkoutKey=null;state.checkoutForm=null;localStorage.removeItem(cartKey()+':checkout');}
let transport;
function demoDb(){let db=read(dbKey,null);if(!db){db={orders:Domain.seed(new Date().toISOString()),requests:{}};write(dbKey,db);}return db;}
async function api(action,payload={}){
 if(gasUrl){transport ||= new PortalTransport.GasBridge(gasUrl);return transport.call({action,token:session?.token,payload});}
 if(action==='login'){if(!['demo123','ops123'].includes(payload.username)||payload.password!=='123456789')throw new Error('帳號或密碼錯誤');return {token:'DEMO-'+uid(),user:{username:payload.username,role:payload.username==='ops123'?'operator':'buyer',company:payload.username==='ops123'?'Demo供應端（示範）':'示範企業股份有限公司'}};}
 if(!session?.token?.startsWith('DEMO-'))throw new Error('登入已失效，請重新登入');
 if(action==='logout')return true;
 const user=session.user,db=demoDb();
 if(action==='bootstrap')return {user,catalog:Domain.products,orders:db.orders.filter(o=>user.role==='operator'||o.owner===user.username)};
 if(action==='checkout'){
   if(user.role!=='buyer')throw new Error('請以採購端帳號下單');
   const key=user.username+':'+payload.requestId;const hash=JSON.stringify({cart:payload.cart,form:payload.form});if(db.requests[key]){const prev=db.requests[key];if(prev.hash!==hash)throw new Error('此下單識別碼已有不同內容，請先確認先前結果，再重新整理購物車');return db.orders.filter(o=>prev.ids.includes(o.id));}
   const orders=Domain.makeOrders(payload.cart,payload.form,Domain.products,user.username,uid().replace(/-/g,''),new Date().toISOString());db.orders.push(...orders);db.requests[key]={ids:orders.map(o=>o.id),hash};write(dbKey,db);return orders;
 }
 if(action==='transition'){
   const o=db.orders.find(x=>x.id===payload.orderId&&(user.role==='operator'||x.owner===user.username));if(!o)throw new Error('訂單不存在');if(o.revision!==payload.revision)throw new Error('訂單已由其他人更新，請重新整理後再操作');Domain.transition(o,payload.itemId,payload.target,payload.input,user.username,user.role,new Date().toISOString());write(dbKey,db);return o;
 }
 throw new Error('不支援的操作');
}
function badge(s){return `<span class="pill s${s}"><i class="dot"></i>${Domain.stages[s]}</span>`;}
function footer(){return `<div class="footer-note"><span>DEMO B2B PROCUREMENT · 企業採購協作平台</span><span>v${esc(PORTAL_CONFIG.version)} · 概念原型 / 所有價格與供應資料皆為示範</span></div>`;}
function login(){
 $('#app').innerHTML=`<div class="login"><section class="login-story">${brand()}<div class="eyebrow">CONNECTED PROCUREMENT</div><h1>每一筆採購，<br>都有清晰的下一步。</h1><p>從產品選型到交貨追蹤，串聯您的需求與供應。讓企業採購更簡單、更透明。</p><div class="login-diagram"><div class="login-node">${icon('tree')}產品選型</div><span class="muted">→</span><div class="login-node">${icon('orders')}協同下單</div><span class="muted">→</span><div class="login-node">${icon('truck')}履約追蹤</div></div><div class="login-foot">POWERING YOUR BUSINESS, TOGETHER.</div></section><main class="login-form-area"><div class="login-box"><div class="eyebrow muted">BUSINESS PARTNER PORTAL</div><h2>歡迎回來</h2><p class="muted">登入企業帳號，管理您的訂單與採購需求。</p><form id="login-form"><label class="field">企業帳號<input name="username" autocomplete="username" value="" required maxlength="40"></label><label class="field">密碼<input name="password" type="password" autocomplete="current-password" value="" required maxlength="200"></label><div class="error" id="login-error" role="alert"></div><button class="btn primary" type="submit">登入企業平台 ${icon('arrow')}</button></form><div class="login-tools"><button type="button" class="link-button" data-action="settings">連線設定</button>${gasUrl?`<button type="button" class="link-button" data-action="connection-popup">以新視窗連線</button>`:''}</div></div></main></div>`;
 $('#login-form').onsubmit=async e=>{e.preventDefault();const b=$('button[type=submit]',e.target);b.disabled=true;$('#login-error').textContent='';try{const data=Object.fromEntries(new FormData(e.target)),s=await api('login',data);session=s;write(sessionKey,s);await load();}catch(err){$('#login-error').textContent=err.message;b.disabled=false;}};
}
async function load(){const data=await api('bootstrap');state.user=data.user;state.user.company=String(state.user.company||'').replace(/台達|delta/gi,'Demo');state.catalog=data.catalog;state.orders=data.orders;state.cart=read(cartKey(),[]);const pending=read(cartKey()+':checkout',null);state.checkoutKey=pending?.key||null;state.checkoutForm=pending?.form||null;render();}
function layout(body){return `<div class="shell ${state.menu?'menu-open':''}"><div class="mobile-sidebar-shade" data-action="menu"></div><aside class="sidebar">${brand()}<button class="nav-main ${state.view==='orders'||state.view==='detail'?'active':''}" data-action="orders">${icon('orders')}訂單管理</button><button class="nav-main ${state.view==='catalog'?'active':''}" data-action="catalog">${icon('tree')}產品型錄</button><div class="nav-separator"></div><div class="nav-label">PRODUCT CATALOG</div><nav class="catalog-nav" aria-label="產品分類">${Domain.categories.map(c=>`<button class="cat-nav ${state.view==='catalog'&&state.category===c.id?'active':''}" data-action="category" data-id="${c.id}">${icon(c.id==='automation'?'factory':c.id==='power'?'bolt':'box')}${c.name}</button>`).join('')}</nav><div class="nav-footer"><div class="avatar">${state.user.role==='operator'?'S':'E'}</div><div><div class="small">${esc(state.user.username)}</div><div style="font-size:10px;margin-top:5px;color:#7e9aae">${state.user.role==='operator'?'供應端管理':'企業採購端'}</div></div><button class="icon-button" style="margin-left:auto" data-action="logout" aria-label="登出">${icon('logout')}</button></div></aside><div class="workspace"><header class="topbar"><div class="crumb"><button class="icon-button menu-toggle" data-action="menu" aria-label="開啟選單">${icon('menu')}</button><span>企業採購平台</span><span>/</span><strong>${{orders:'訂單管理',catalog:'產品型錄',detail:'訂單詳情',cart:'購物車'}[state.view]}</strong></div><div class="top-actions"><span class="connection ${gasUrl?'':'demo'}"><i class="dot"></i>${gasUrl?'GAS 已連線':'本機示範模式'}</span><button class="icon-button" data-action="settings" aria-label="連線設定">${icon('settings')}</button><button class="icon-button cart-button" data-action="cart" aria-label="購物車">${icon('cart')}${state.cart.length?`<span class="count">${state.cart.length}</span>`:''}</button><div class="avatar">${state.user.role==='operator'?'S':'E'}</div></div></header><main class="content">${body}${footer()}</main></div></div>`;}
function heading(title,eyebrow,desc,buttons=''){return `<div class="page-heading"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p>${desc}</p></div><div class="heading-buttons">${buttons}</div></div>`;}
function ordersView(){
 const os=state.orders,ag=os.map(Domain.aggregate),active=os.filter((o,i)=>ag[i].status<4),review=ag.filter(a=>a.status===0).length,production=ag.filter(a=>a.status===2).length,shipped=ag.filter(a=>a.status===4).length;
 const filtered=os.filter(o=>{const a=Domain.aggregate(o);return (state.filter==='all'||a.status===Number(state.filter))&&(!state.search||[o.id,o.po,Domain.typeName(o.type),...o.items.map(i=>i.name+' '+i.sku)].join(' ').toLowerCase().includes(state.search.toLowerCase()));}).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||a.id.localeCompare(b.id));
 const pages=Math.max(1,Math.ceil(filtered.length/8));state.page=Math.min(state.page,pages);const rows=filtered.slice((state.page-1)*8,state.page*8);
 return heading('訂單管理','ORDER WORKSPACE',`掌握每一筆採購的履約進度，讓需求與交付保持同步。`,`${state.user.role==='buyer'?`<button class="btn primary" data-action="catalog">${icon('grid')}開始採購</button>`:''}<button class="btn" data-action="refresh">${icon('refresh')}重新整理</button>`)+
 `<div class="cards"><div class="metric"><div class="metric-label">進行中訂單 ${icon('orders')}</div><div class="value">${active.length}<span style="font-size:12px;margin-left:8px;color:#91a9bc">筆</span></div><div class="caption">待審核、備料、生產及入庫</div></div><div class="metric"><div class="metric-label">待審核 ${icon('clock')}</div><div class="value">${review}</div><div class="caption">等待價格與交期確認</div></div><div class="metric"><div class="metric-label">生產中 ${icon('factory')}</div><div class="value">${production}</div><div class="caption">以訂單最慢明細計算</div></div><div class="metric"><div class="metric-label">已完成出貨 ${icon('truck')}</div><div class="value">${shipped}</div><div class="caption">有效明細皆已全數出貨</div></div></div>
 <div class="workflow-strip"><span class="flow-title">履約生命週期</span>${Domain.stages.slice(0,5).map((s,i)=>`<div class="flow-step"><span class="flow-number">${String(i+1).padStart(2,'0')}</span>${s}</div>`).join('')}<div class="flow-step" style="color:#b47f8c">${icon('x')}訂單中止</div></div>
 <section class="panel"><div class="panel-header"><div><h2>訂單總覽 <span class="stat-number">${os.length}</span></h2></div><span class="small muted">${esc(state.user.company)}</span></div><div class="toolbar"><div class="tabs" role="tablist">${['全部',...Domain.stages].map((s,i)=>{const key=i===0?'all':String(i-1),count=i===0?os.length:ag.filter(a=>a.status===i-1).length;return `<button class="tab ${state.filter===key?'active':''}" role="tab" aria-selected="${state.filter===key}" data-action="filter" data-id="${key}">${s}<span>${count}</span></button>`;}).join('')}</div><div class="searchbox">${icon('search')}<input id="order-search" class="search" placeholder="搜尋訂單、PO 或產品" aria-label="搜尋訂單" value="${esc(state.search)}"></div></div><div id="order-results"><div class="table-scroll"><table><thead><tr><th>訂單編號 / 採購單號</th><th>產品類型</th><th>訂單狀態</th><th>需求日期</th><th>有效訂單金額</th><th>履約進度</th><th></th></tr></thead><tbody>${rows.map(o=>{const a=Domain.aggregate(o);return `<tr><td><button class="order-link mono" data-action="detail" data-id="${esc(o.id)}">${esc(o.id)}</button><div class="secondary">${esc(o.po)}</div></td><td>${esc(Domain.typeName(o.type))}<div class="secondary">${o.items.length} 個明細 · ${o.items.reduce((s,i)=>s+i.qty,0)} 件</div></td><td>${badge(a.status)}${a.halted&&a.status!==5?`<div class="inline-tag">${a.halted} 筆明細已中止</div>`:''}${a.partialShipped?'<div class="inline-tag">部分出貨</div>':''}</td><td class="mono">${esc(o.needDate)}</td><td class="mono">${money(a.activeTotal)}</td><td><span class="small muted">${a.progress}%</span><div class="progress"><div style="width:${a.progress}%"></div></div></td><td><button class="icon-button" data-action="detail" data-id="${esc(o.id)}" aria-label="查看訂單 ${esc(o.id)}">${icon('arrow')}</button></td></tr>`;}).join('')}</tbody></table>${rows.length?'':`<div class="empty">${icon('orders')}<p>沒有符合條件的訂單</p><button class="btn sm" data-action="clear-filter">清除篩選</button></div>`}</div><div class="panel-footer"><span>共 ${filtered.length} 筆訂單 · 頁面 ${state.page} / ${pages}</span><div><button class="icon-button" data-action="prev" aria-label="上一頁" ${state.page===1?'disabled':''}>${icon('back')}</button><button class="icon-button" data-action="next" aria-label="下一頁" ${state.page===pages?'disabled':''}>${icon('arrow')}</button></div></div></div></section><p class="source-note">訂單總狀態取有效明細的最慢進度；全部中止時才顯示「訂單中止」。金額為未稅示範價格。</p>`;
}
function productArt(p){return `<div class="device ${['hmi','plc','adapter','fan'].includes(p.type)?'wide':['ups','ev'].includes(p.type)?'big':''}"><div class="screen">${p.type==='drive'?'50.00':'DEMO'}</div><div class="vents"></div><div class="device-label">${esc(p.type.toUpperCase())}</div></div>`;}
function catalogView(){
 const products=state.catalog.filter(p=>p.active!==false&&(state.category==='all'||p.category===state.category)&&(state.type==='all'||p.type===state.type)&&(!state.productSearch||[p.name,p.sku,p.description].join(' ').toLowerCase().includes(state.productSearch.toLowerCase()))),cat=Domain.categories.find(c=>c.id===state.category);
 return heading('產品型錄','PRODUCT CATALOG','依產品分類探索，選擇適合您企業的採購配置。',`<button class="btn" data-action="orders">${icon('back')}回到訂單管理</button><button class="btn primary" data-action="cart">${icon('cart')}購物車 ${state.cart.length?`(${state.cart.length})`:''}</button>`)+`<div class="notice">${icon('info')}<span>依產品用途與類型分類。系列名稱供選型參考；DEMO 料號、價格、最小訂購量與交期皆為示範，實際交易需確認正式規格及報價。</span></div><div class="catalog-layout"><aside class="tree-panel"><h3>${icon('tree')}　產品分類樹狀圖</h3><button class="tree-leaf ${state.category==='all'?'active':''}" style="margin-left:0;width:100%" data-action="catalog">全部產品 <span class="stat-number">${state.catalog.filter(p=>p.active!==false).length}</span></button>${['電源及零組件','交通','自動化','基礎設施'].map(s=>`<div class="tree-root">${s}</div>${Domain.categories.filter(c=>c.sector===s).map(c=>`<details ${c.id===state.category||state.category==='all'?'open':''}><summary>${c.name}</summary>${c.types.map(t=>`<button class="tree-leaf ${state.type===t[0]?'active':''}" data-action="type" data-id="${t[0]}" data-category="${c.id}">${t[1]} <span class="muted small">${state.catalog.filter(p=>p.type===t[0]&&p.active!==false).length}</span></button>`).join('')}</details>`).join('')}`).join('')}</aside><section><div class="catalog-tools"><div><h2>${state.type!=='all'?esc(Domain.typeName(state.type)):cat?cat.name:'全部產品'}</h2><p class="small muted" style="margin-top:7px">${products.length} 項可選購配置</p></div><div class="searchbox">${icon('search')}<input class="search" id="product-search" placeholder="搜尋系列或料號" aria-label="搜尋產品" value="${esc(state.productSearch)}"></div></div><div class="product-grid">${products.map(p=>`<article class="product-card"><div class="product-visual"><span class="visual-tag">${esc(Domain.typeName(p.type))}</span>${productArt(p)}<span class="visual-demo">產品示意圖</span></div><div class="product-body"><div class="sku mono">${esc(p.sku)}</div><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="price">${money(p.price)}<span class="small muted"> / 件</span></div><div class="product-meta"><span>MOQ ${p.moq} 件</span><span>示範交期 ${p.leadDays} 天</span></div><div class="product-bottom"><button class="btn sm" data-action="product" data-id="${esc(p.id)}">查看產品</button><button class="btn primary sm" data-action="add" data-id="${esc(p.id)}" ${state.user.role!=='buyer'?'disabled':''}>${icon('cart')}加入</button></div></div></article>`).join('')}</div>${products.length?'':'<div class="empty">找不到符合條件的產品</div>'}</section></div>`;
}
function datum(k,v){return `<div><div class="datum-label">${k}</div><div class="datum-value">${esc(v??'—')}</div></div>`;}
function itemInfo(o,i){const d=i.details,arr=[datum('訂購量 / 示範單價',i.qty+' 件 / '+money(i.price)),datum('已完工 / 已出貨',i.completedQty+' / '+i.shippedQty+' 件'),datum('需求日期',o.needDate)];
 if(i.status===0)arr.push(datum('審核重點','價格、需求日期與供應可行性'),datum('交易條件','TWD / 未稅 / 月結 30 天（示範）'),datum('交期確認','等待供應端承諾'));
 if(d.materialRef)arr.push(datum('備料單 / 齊套',d.materialRef+' / '+(d.kitReady?'已齊套':'未齊套')),datum('承諾交期',d.committedDate));
 if(d.workOrder)arr.push(datum('生產工單',d.workOrder),datum('生產開始',d.productionStart));
 if(d.warehouse)arr.push(datum('倉別',d.warehouse),datum('庫存批號',d.lot),datum('品質放行',d.qualityReleased?'已放行':'待確認'));
 if(d.stopReason)arr.push(datum('中止原因',d.stopReason));return arr.join('');}
function detailView(){const o=state.orders.find(x=>x.id===state.orderId);if(!o){state.view='orders';return ordersView();}const a=Domain.aggregate(o),operator=state.user.role==='operator';
 return `<button class="back-link" data-action="orders">${icon('back')}返回訂單總覽</button>`+heading(esc(o.id),'ORDER DETAILS',`${esc(Domain.typeName(o.type))} · ${o.items.length} 個明細 · ${esc(o.po)}`,`<button class="btn" data-action="refresh">${icon('refresh')}重新整理</button>`)+`<div class="status-info">${badge(a.status)}　${a.status===5?'此訂單所有明細皆已中止。':'總狀態依有效明細的最慢進度彙總，每個明細可獨立推進。'}${a.halted&&a.status!==5?` ${a.halted} 筆明細已中止。`:''}${a.partialShipped?' 目前為部分出貨。':''}</div><div class="detail-grid"><section class="panel"><div class="panel-header"><h2>訂單明細與履約進度</h2><span class="small muted">版本 ${o.revision}</span></div>${o.items.map(i=>`<article class="item-card"><div class="item-header"><div class="item-name"><div class="item-icon">${icon('box')}</div><div><div class="item-title">${esc(i.name)}</div><div class="item-meta mono">${esc(i.id)} · ${esc(i.sku)}</div></div></div><div class="item-actions">${badge(i.status)}${operator&&i.status<4?`<button class="btn primary sm" data-action="advance" data-id="${esc(i.id)}">${i.status===3?'安排出貨':`推進至${Domain.stages[i.status+1]}`} ${icon('arrow')}</button>`:''}${(operator&&i.status<4||!operator&&i.status===0)&&i.shippedQty===0?`<button class="btn danger sm" data-action="stop" data-id="${esc(i.id)}">中止明細</button>`:''}</div></div>${i.status===5?'':`<div class="item-flow">${Domain.stages.slice(0,5).map((s,j)=>`<div class="item-flow-step ${j<=i.status?'done':''} ${j===i.status?'current':''}"><span class="flow-number">${j<i.status?icon('check'):j+1}</span>${s}</div>`).join('')}</div>`}<div class="item-data" style="${i.status===5?'margin-top:20px':''}">${itemInfo(o,i)}</div>${(i.details.shipments||[]).map(s=>`<div class="shipment-row">${icon('truck')} <b>${esc(s.delivery)}</b> · ${s.qty} 件 · ${esc(s.carrier)}<br>追蹤資訊：${esc(s.tracking)} · ${fmt(s.at)}</div>`).join('')}<details class="timeline"><summary>查看生命週期紀錄 (${i.history.length})</summary><ol>${i.history.slice().reverse().map(h=>`<li><b>${Domain.stages[h.status]}</b> · ${fmt(h.at)}<br>${esc(h.note)}<br><span class="muted">操作人：${esc(h.actor)}</span></li>`).join('')}</ol></details></article>`).join('')}</section><aside><section class="panel detail-summary"><div class="order-amount"><div class="datum-label">有效訂單金額（未稅示範）</div>${money(a.activeTotal)}</div>${[['採購單號',o.po],['購物車批次',o.batchId],['採購帳號',o.owner],['聯絡人',o.contact],['收貨地址',o.address],['需求日期',o.needDate],['建立時間',fmt(o.createdAt)],['原始金額',money(a.total)],['備註',o.note||'—']].map(([k,v])=>`<div class="summary-line"><span>${k}</span><strong>${esc(v)}</strong></div>`).join('')}</section><section class="panel help-box" style="margin-top:18px">${icon('info')}　角色與操作<br>${operator?'供應端可依序更新各明細狀態，備料、入庫及出貨皆需提供佐證欄位。':'採購端可查看全流程；僅審核中的明細可直接中止，後續異動由供應端協調。'}<br>已出貨與已中止為終點，不能倒退。部分出貨的明細維持已入庫。</section></aside></div>`;
}
function cartProducts(){return state.cart.map(c=>({cart:c,product:state.catalog.find(p=>p.id===c.productId)})).filter(x=>x.product);}
function cartView(){const ps=cartProducts(),groups={};ps.forEach(x=>{(groups[x.product.type]||= []).push(x);});const total=ps.reduce((s,x)=>s+x.product.price*x.cart.qty,0);
 return heading('採購購物車','PROCUREMENT CART','集中選購，依產品類型自動拆成獨立訂單。',`<button class="btn" data-action="catalog">${icon('back')}繼續選購</button>`)+(!ps.length?`<section class="panel empty">${icon('cart')}<p>購物車目前沒有產品</p><button class="btn primary" data-action="catalog">瀏覽產品型錄</button></section>`:`<div class="cart-layout"><section><div class="panel"><div class="panel-header"><h2>採購明細 <span class="stat-number">${ps.length}</span></h2><span class="small muted">同一產品合併數量</span></div>${ps.map(({cart:c,product:p})=>`<div class="cart-row"><div class="item-name"><div class="item-icon">${icon('box')}</div><div><div class="item-title">${esc(p.name)}</div><div class="item-meta">${esc(p.sku)} · ${esc(Domain.typeName(p.type))}</div></div></div><div><input class="qty" type="number" min="${p.moq}" step="${p.moq}" max="100000" data-qty="${esc(p.id)}" aria-label="${esc(p.name)} 的數量" value="${c.qty}"><div class="small muted" style="margin-top:5px">MOQ ${p.moq} 件</div></div><div class="mono">${money(p.price*c.qty)}</div><button class="icon-button" data-action="remove" data-id="${esc(p.id)}" aria-label="移除 ${esc(p.name)}">${icon('trash')}</button></div>`).join('')}</div><div class="panel" style="margin-top:22px"><div class="panel-header"><h2>拆單預覽</h2><span class="small muted">${Object.keys(groups).length} 筆獨立訂單</span></div>${Object.keys(groups).map(t=>`<div class="split-preview"><span>${icon('orders')}　${esc(Domain.typeName(t))} · ${groups[t].length} 個明細</span><span class="mono">${money(groups[t].reduce((s,x)=>s+x.product.price*x.cart.qty,0))}</span></div>`).join('')}<div class="help-box">同一產品類型合併為一張訂單，每個產品保留獨立明細。拆分後以同一批次號連結，採購單號、收貨地址與需求日期共用。</div></div></section><aside class="panel checkout-form"><h2 style="margin-bottom:22px">採購資訊</h2><form id="checkout-form"><label class="field">企業採購單號 / PO<input name="po" required maxlength="80" placeholder="例：PO-2026-001"></label><label class="field">需求日期<input type="date" name="needDate" required min="${today()}" value="${today()}"></label><label class="field">聯絡人與電話<input name="contact" required maxlength="80" placeholder="姓名 / 聯絡電話"></label><label class="field">收貨地址<input name="address" required maxlength="300" placeholder="完整收貨地址"></label><label class="field">備註<textarea name="note" maxlength="500" placeholder="專案需求、交貨注意事項"></textarea></label><div class="summary-line" style="border-top:1px solid var(--line);padding-top:18px;margin-top:10px"><span>示範未稅總額</span><b class="mono">${money(total)}</b></div><label class="check"><input type="checkbox" name="ack" required><span>確認產品、數量及拆單結果。價格與交期須待供應端審核。</span></label><div class="form-error" id="checkout-error" role="alert"></div><button class="btn primary full-width" type="submit" ${state.user.role!=='buyer'?'disabled':''}>送出 ${Object.keys(groups).length} 筆訂單 ${icon('arrow')}</button><p class="source-note">此版下單不收取付款；流程從「審核中」開始。</p></form></aside></div>`);
}
function render(){if(!state.user)return login();$('#app').innerHTML=layout(({orders:ordersView,catalog:catalogView,detail:detailView,cart:cartView}[state.view]||ordersView)());
 const search=$('#order-search');if(search)search.oninput=e=>{const pos=e.target.selectionStart;state.search=e.target.value;state.page=1;render();const n=$('#order-search');n.focus();n.setSelectionRange(pos,pos);};
 const productSearch=$('#product-search');if(productSearch)productSearch.oninput=e=>{const pos=e.target.selectionStart;state.productSearch=e.target.value;render();const n=$('#product-search');n.focus();n.setSelectionRange(pos,pos);};
 const checkout=$('#checkout-form');if(checkout){if(state.checkoutForm)Object.entries(state.checkoutForm).forEach(([k,v])=>{const el=checkout.elements[k];if(el){if(el.type==='checkbox')el.checked=!!v;else el.value=v;}});checkout.oninput=()=>{state.checkoutForm=Object.fromEntries(new FormData(checkout));};checkout.onsubmit=submitCheckout;}
}
function showModal(title,body,onSubmit){modalPreviousFocus=document.activeElement;$('#modal-root').innerHTML=`<div class="modal-overlay"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header class="modal-header"><h2 id="modal-title">${title}</h2><button class="icon-button" data-action="close-modal" aria-label="關閉">${icon('x')}</button></header><div class="modal-body">${body}</div></section></div>`;
 const form=$('form',$('#modal-root'));if(form&&onSubmit)form.onsubmit=async e=>{e.preventDefault();const button=$('button[type=submit]',form);button.disabled=true;const error=$('.form-error',form);if(error)error.textContent='';try{await onSubmit(Object.fromEntries(new FormData(form)));}catch(err){if(error)error.textContent=err.message;else toast(err.message);}finally{if(button.isConnected)button.disabled=false;}};
 setTimeout(()=>$('input,select,textarea,button',$('.modal-body'))?.focus(),0);
}
function closeModal(){if(busy)return;$('#modal-root').innerHTML='';modalPreviousFocus?.focus();}
function modalActions(label){return `<div class="form-error" role="alert"></div><div class="modal-footer"><button type="button" class="btn" data-action="close-modal">取消</button><button type="submit" class="btn primary">${label}</button></div>`;}
function productModal(id){const p=state.catalog.find(p=>p.id===id);if(!p)return;showModal(esc(p.name),`<div class="product-modal-art">${productArt(p)}</div><p class="muted" style="line-height:1.8">${esc(p.description)} · ${esc(p.tag)}</p><div class="item-data" style="margin:20px 0">${datum('示範料號',p.sku)}${datum('產品類型',Domain.typeName(p.type))}${datum('未稅示範單價',money(p.price))}${datum('最小訂購量',p.moq+' 件')}${datum('示範交期',p.leadDays+' 天')}</div><a href="${esc(p.source)}" target="_blank" rel="noopener">查看官方產品分類 ${icon('external')}</a><p class="source-note">此版為系列層級示範配置，尚未導入完整規格選型；圖形為示意，非正式產品外觀。</p><div class="modal-footer"><button class="btn" data-action="close-modal">關閉</button><button class="btn primary" data-action="add" data-id="${esc(p.id)}" ${state.user.role!=='buyer'?'disabled':''}>加入購物車</button></div>`);}
function transitionModal(itemId,stop=false){const o=state.orders.find(x=>x.id===state.orderId),i=o.items.find(x=>x.id===itemId),n=stop?5:i.status+1;
 let fields='';if(stop)fields=`<div class="notice">${icon('info')}中止後保留歷史紀錄，不能直接恢復。已部分出貨的明細需另行協調。</div><label class="field">中止原因<textarea name="note" required maxlength="500" placeholder="說明異動原因"></textarea></label>`;
 else if(n===1)fields=`<div class="notice">${icon('info')}請先核對客戶 PO、價格、需求日期與供應可行性，再確認備料。</div><label class="field">備料 / 預留單號<input name="materialRef" required maxlength="80" placeholder="MR-2026-001"></label><label class="field">承諾交期<input type="date" name="committedDate" required value="${esc(o.needDate)}"></label><label class="check"><input type="checkbox" name="kitReady" required>已確認交易條件及物料齊套</label>`;
 else if(n===2)fields=`<label class="field">生產工單號<input name="workOrder" required maxlength="80" placeholder="WO-2026-001"></label><label class="field">生產開始日期<input type="date" name="productionStart" required value="${today()}"></label>`;
 else if(n===3)fields=`<div class="notice">${icon('info')}此版採全數完工入庫。可在入庫後分批出貨。</div><label class="field">完工數量<input type="number" name="completedQty" min="${i.qty}" max="${i.qty}" required value="${i.qty}"></label><div class="form-grid"><label class="field">入庫倉別<input name="warehouse" required maxlength="80" placeholder="成品倉"></label><label class="field">庫存批號<input name="lot" required maxlength="80" placeholder="LOT-2026-001"></label></div><label class="check"><input type="checkbox" name="qualityReleased" required>已完成品質檢驗並放行</label>`;
 else fields=`<div class="notice">${icon('info')}尚未出貨 ${i.qty-i.shippedQty} 件。部分出貨維持「已入庫」，全數出貨才轉為「已出貨」。</div><label class="field">本次出貨數量<input name="shipQty" type="number" min="1" max="${i.qty-i.shippedQty}" required value="${i.qty-i.shippedQty}"></label><label class="field">交貨單號<input name="delivery" required maxlength="80" placeholder="DN-2026-001"></label><label class="field">物流商<input name="carrier" required maxlength="80" placeholder="物流商名稱"></label><label class="field">追蹤資訊 / 提單號<input name="tracking" required maxlength="100" placeholder="物流追蹤號碼"></label>`;
 if(!stop)fields+=`<label class="field">操作備註<textarea name="note" maxlength="500" placeholder="補充說明（選填）"></textarea></label>`;
 showModal(stop?'中止訂單明細':n===4?'安排出貨':`更新為${Domain.stages[n]}`,`<p class="small muted" style="margin-bottom:20px">${esc(i.name)} · ${esc(i.id)}</p><form>${fields}${modalActions(stop?'確認中止':'確認更新')}</form>`,async data=>{
   const input={...data,kitReady:!!data.kitReady,qualityReleased:!!data.qualityReleased};const target=!stop&&n===4&&Number(data.shipQty)+i.shippedQty<i.qty?3:n;
   busy=true;try{const updated=await api('transition',{orderId:o.id,itemId:i.id,target,input,revision:o.revision});state.orders=state.orders.map(x=>x.id===updated.id?updated:x);busy=false;closeModal();render();toast('明細狀態已更新');}finally{busy=false;}
 });
}
function settings(){showModal('連線與示範設定',`<div class="notice">${icon('info')}設定企業平台資料連線，儲存後重新登入。</div><form><label class="field">GAS 網頁應用程式網址<input name="url" type="url" value="${esc(gasUrl)}" placeholder="https://script.google.com/macros/s/…/exec"></label><p class="source-note">GAS 允許來源請填：<b>${esc(location.origin)}</b><br>變更連線會登出並重新載入。</p>${modalActions('儲存連線設定')}</form>${gasUrl?`<div class="settings-actions"><button class="btn" data-action="test-connection">測試連線</button><button class="btn" data-action="connection-popup">以新視窗連線</button></div><div id="connection-result" class="small" role="status"></div>`:''}${state.user?`<div class="settings-actions"><button class="btn" data-action="switch-role">${icon('user')}登出並切換為${state.user.role==='buyer'?'供應端':'採購端'}</button>${!gasUrl?`<button class="btn danger" data-action="reset-demo">重設本機示範訂單</button>`:''}</div>`:''}<p class="source-note"></p>`,async data=>{const value=data.url.trim();if(value&&!/^https:\/\/script\.google\.com\/macros\/s\/[A-Za-z0-9_-]+\/exec$/.test(value))throw new Error('請使用 GAS 正式部署的 /exec 網址');if(session)try{await api('logout');}catch{}localStorage.removeItem(sessionKey);write('demo-b2b-url',value);location.reload();});}
async function submitCheckout(e){e.preventDefault();if(busy)return;const f=e.target,button=$('button[type=submit]',f);button.disabled=true;$('#checkout-error').textContent='';state.checkoutForm=Object.fromEntries(new FormData(f));state.checkoutKey ||= uid();write(cartKey()+':checkout',{key:state.checkoutKey,form:state.checkoutForm});busy=true;
 try{const created=await api('checkout',{cart:state.cart,form:state.checkoutForm,requestId:state.checkoutKey});state.orders=state.orders.filter(o=>!created.some(n=>n.id===o.id)).concat(created);state.cart=[];saveCart();state.view='orders';state.filter='0';state.search='';state.page=1;render();showModal('採購需求已送出',`<div class="success-box">${icon('check')}　已依產品類型建立 <b>${created.length}</b> 筆訂單<br>全部從「審核中」開始，各明細獨立追蹤。</div>${created.map(o=>`<div class="split-preview"><div><b>${esc(Domain.typeName(o.type))}</b><p class="small mono muted" style="margin-top:6px">${esc(o.id)}</p></div><button class="btn sm" data-action="detail" data-id="${esc(o.id)}">查看</button></div>`).join('')}<div class="modal-footer"><button class="btn primary" data-action="close-modal">回到訂單總覽</button></div>`);
 }catch(err){if($('#checkout-error'))$('#checkout-error').textContent=err.message;else toast(err.message);}finally{busy=false;if(button.isConnected)button.disabled=false;}
}
async function refresh(silent=false){if(busy)return;const data=await api('bootstrap'),changed=JSON.stringify(state.orders)!==JSON.stringify(data.orders)||JSON.stringify(state.catalog)!==JSON.stringify(data.catalog);state.orders=data.orders;state.catalog=data.catalog;if(!silent||changed){if(!$('#modal-root').innerHTML&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))render();if(!silent)toast('訂單已同步');else if(changed)toast('供應端進度已更新');}}
async function logout(next='demo123'){if(session)try{await api('logout');}catch{}session=null;localStorage.removeItem(sessionKey);state.user=null;state.view='orders';state.menu=false;$('#modal-root').innerHTML='';login(next);}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled||busy)return;const a=b.dataset.action,id=b.dataset.id;
 try{
 if(a==='settings')return settings();if(a==='test-connection'){const result=$('#connection-result');if(result)result.textContent='檢測中…';const info=await PortalTransport.healthCheck(gasUrl);const message=!info.originAllowed?'來源未允許：請將 '+location.origin+' 加入 ALLOWED_ORIGINS':!info.databaseConfigured?'資料庫尚未初始化，請執行 setup':'部署 '+info.version+' 可存取，來源與資料庫設定正常';if(result)result.textContent=message;else toast(message);return;}if(a==='connection-popup'){transport ||= new PortalTransport.GasBridge(gasUrl);toast('正在建立新視窗連線…');await transport.connect('popup');toast('已連線，請保留連線視窗並重新登入');return;}if(a==='close-modal')return closeModal();if(a==='logout')return logout();if(a==='switch-role')return logout(state.user.role==='buyer'?'ops123':'demo123');
 if(a==='reset-demo')return showModal('重設示範資料',`<p class="muted" style="line-height:1.9">這會清除本機示範訂單，重新建立初始範例。已連線的 GAS 資料不受影響。</p><form>${modalActions('確認重設')}</form>`,async()=>{localStorage.removeItem(dbKey);state.orders=demoDb().orders;closeModal();await refresh();});
 if(a==='menu'){state.menu=!state.menu;render();return;}
 if(a==='orders'){state.view='orders';state.menu=false;closeModal();render();}
 if(a==='catalog'||a==='category'||a==='type'){state.view='catalog';state.menu=false;state.productSearch='';state.category=a==='catalog'?'all':a==='category'?id:b.dataset.category;state.type=a==='type'?id:'all';closeModal();render();}
 if(a==='cart'){state.view='cart';state.menu=false;closeModal();render();}
 if(a==='filter'){state.filter=id;state.page=1;render();}
 if(a==='clear-filter'){state.filter='all';state.search='';state.page=1;render();}
 if(a==='detail'){state.orderId=id;state.view='detail';closeModal();render();}
 if(a==='prev'||a==='next'){state.page+=a==='prev'?-1:1;render();}
 if(a==='refresh'){busy=true;b.disabled=true;try{const data=await api('bootstrap');state.orders=data.orders;state.catalog=data.catalog;render();toast('訂單已同步');}finally{busy=false;if(b.isConnected)b.disabled=false;}}
 if(a==='product')productModal(id);
 if(a==='add'){if(state.user.role!=='buyer')throw new Error('請以採購端帳號下單');const p=state.catalog.find(p=>p.id===id),c=state.cart.find(c=>c.productId===id);if(!p||p.active===false)throw new Error('產品已下架');if(c){if(c.qty+p.moq>100000)throw new Error('數量超過上限');c.qty+=p.moq;}else state.cart.push({productId:id,qty:p.moq});saveCart();render();toast(p.name+' 已加入購物車');}
 if(a==='remove'){state.cart=state.cart.filter(c=>c.productId!==id);saveCart();render();}
 if(a==='advance'||a==='stop')transitionModal(id,a==='stop');
 }catch(err){toast(err.message);}
});
document.addEventListener('change',e=>{const id=e.target.dataset.qty;if(!id)return;const p=state.catalog.find(p=>p.id===id),c=state.cart.find(c=>c.productId===id),n=Number(e.target.value);if(!Number.isSafeInteger(n)||n<p.moq||n>100000||n%p.moq!==0){e.target.value=c.qty;toast('數量須為 '+p.moq+' 的倍數，且不超過 100000');return;}c.qty=n;saveCart();render();});
document.addEventListener('keydown',e=>{if(!$('#modal-root').innerHTML)return;if(e.key==='Escape')closeModal();if(e.key==='Tab'){const els=Array.from($('#modal-root').querySelectorAll('button:not(:disabled),a,input,select,textarea')).filter(x=>x.offsetParent!==null),first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
async function start(){if(session){$('#app').innerHTML='<main style="min-height:100vh;display:grid;place-items:center" aria-busy="true"><div style="text-align:center"><div class="spinner" style="margin:0 auto 18px"></div><p class="muted">正在同步企業訂單…</p></div></main>';try{await load();}catch(err){session=null;localStorage.removeItem(sessionKey);login();$('#login-error').textContent=err.message;}}else login();}
setInterval(()=>{if(state.user&&document.visibilityState==='visible'&&!busy&&!$('#modal-root').innerHTML)refresh(true).catch(e=>toast(e.message));},Math.max(15,PORTAL_CONFIG.refreshSeconds||30)*1000);
start();
})();
